import builtins
import uuid

class UUID7Obj:
    @property
    def int(self) -> builtins.int: ...
    @property
    def bytes(self) -> builtins.bytes: ...
    @property
    def bytes_le(self) -> builtins.bytes: ...
    @property
    def hex(self) -> builtins.str: ...
    @property
    def time(self) -> builtins.int: ...
    @property
    def timestamp(self) -> builtins.int: ...
    @property
    def urn(self) -> builtins.str: ...
    @property
    def version(self) -> builtins.int: ...
    @property
    def variant(self) -> builtins.str: ...
    @property
    def fields(
        self,
    ) -> tuple[
        builtins.int,
        builtins.int,
        builtins.int,
        builtins.int,
        builtins.int,
        builtins.int,
    ]: ...
    def __str__(self) -> builtins.str: ...
    def __int__(self) -> builtins.int: ...
    def __bytes__(self) -> builtins.bytes: ...
    def __index__(self) -> builtins.int: ...

def uuid7() -> uuid.UUID: ...
def uuid7_obj() -> UUID7Obj: ...
def uuid7_str() -> builtins.str: ...
def uuid7_bytes() -> builtins.bytes: ...
def uuid7_many(count: builtins.int) -> list[uuid.UUID]: ...
def uuid7_obj_many(count: builtins.int) -> list[UUID7Obj]: ...
def uuid7_str_many(count: builtins.int) -> list[builtins.str]: ...
def uuid7_bytes_many(count: builtins.int) -> builtins.bytes: ...

__version__: builtins.str
